# my global config
global:
    scrape_interval: 15s # By default, scrape targets every 15 seconds.
    evaluation_interval: 15s # By default, scrape targets every 15 seconds.
    # scrape_timeout is set to the global default (10s).

    # Attach these labels to any time series or alerts when communicating with
    # external systems (federation, remote storage, Alertmanager).
    external_labels:
        monitor: 'my-project'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
    - 'alert.rules.yml'
    # - "first.rules"
    # - "second.rules"

# alert
# alerting:
#   alertmanagers:
#   - scheme: http
#     static_configs:
#     - targets:
#       - "alertmanager:9093"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
    #? Thu thập số liệu từ chính Prometheus trên localhost:9090 mỗi 5 giây.
    - job_name: 'prometheus'
      scrape_interval: 5s
      static_configs:
          - targets: ['localhost:9090']

    #? Thu thập số liệu từ Traefik sử dụng DNS service discovery để tìm các mục tiêu với tên DNS tasks.traefik trên cổng 8080 mỗi 5 giây.
    - job_name: 'traefik'
      scrape_interval: 5s
      #? thu thập số liệu từ dynamic targets sử dụng DNS service discovery.
      dns_sd_configs:
          #/  tìm các mục tiêu bằng tên DNS tasks.traefik.
          - names:
                - 'tasks.traefik'
            type: 'A' #/chỉ ra loại bản ghi DNS để tìm kiếm. A là bản ghi địa chỉ IPv4.
            port: 8080
#? docker-compose không hỗ trợ tạo dns
#? Docker Swarm, Docker Swarm sẽ tạo ra các bản ghi DNS tasks.traefik cho mỗi bản sao của dịch vụ có tên "traefik" đó.
#? Kubernetes sử dụng các bản ghi DNS khác nhau, thường là *.svc.cluster.local cho các dịch vụ trong cluster.
